# Parameter set for CoCEL Handheld Indoor environment

# topic: /livox/points (set in launch file or command line)

deskew: true
max_range: 200
min_range: 1
voxel_size: 0.6
desired_num_voxelized_points: 2500
planarity_threshold: 0.25
max_points_per_voxel: 5
initial_threshold: 2.0
min_motion_th: 0.1
max_num_iterations: 150
convergence_criterion: 0.0001